### PR TITLE
Pr/show result for each expectation assertion in the spec

### PR DESCRIPTION
**Pull request by bongosway**
@Evilweed I have created this PR, so we can talk through it.
So far I have added the collapse class to the Results table, but not sure what summary information is wanted on there. 
I have asked the same question on the issue tracker but no response yet.

Thanks for your time and help.

### CODE REVIEW

**Comment by Evilweed** [comment]
If test case contains multiple expectations:
```
it('is valid account', () => {
    expect(account.type.getText()).toBe(testData.type);
    expect(account.size.getText()).toBe(testData.size);
});
```
then for that test cases, unwrapping should reveal list of expectations with each having:
- Expectation status (passed/failed)
- Expectation message (expected something to contain something)
- Time
- Link to stack
- Link to browser log

I didn't think it through - but something similar to this:
Example

**Comment by bongosway** [comment]
Just got back to this due to time reasons.
From your example, I think it is anti-pattern to have two expects in one *it* block.
To be honest, I think this library is fine as it is having look through in the internal, not really seen the use case especially as relates to Jasmine. 
I am open to be corrected on this. Will continue if you want, but for now will hold off.

Kind Regards.

**Comment by Evilweed** [comment]
@bongosway honestly I have the same opinion - but some User requested this feature :) It's not something super important but if You have time and would like to do it then go ahead.

**Comment by Evilweed** [comment]
Closing as per comment above.

**Pull request closed without merging**
