### PR TITLE
Add ability to use left/right arrows to navigate image modals

### PR DESCRIPTION
**Pull request by RonanDConnolly**
Solution for issue: #151 

## The solution
I've added keydown event listener on the modal itself (will only trigger when the modal is open).
It hides the old modal and shows the new one based on the index and whether a left or right arrow key was pressed.

This will allow quick navigation between screenshots.

### CODE REVIEW

**Comment by RonanC** [comment]
I looked at the tests and wasn't entirely sure the best approach to test this.
Would we want to spy on the `showHideModal` method and also the actual modal?

Here's my brief attempt at putting something together:
```js
           describe("#updateSelectedModal()", function () {
                it('should hide one modal and show another', function () {
                    // Arrange
                    var $scope = $rootScope.$new();
                    var controller = $controller('ScreenshotReportController', {$scope: $scope});
                    controller.results = [
                        0, 1, 2
                    ];
                    
                    // Act
                    controller.updateSelectedModal({keyCode: 37}, 0);
                    controller.updateSelectedModal({keyCode: 37}, 1);
                    controller.updateSelectedModal({keyCode: 39}, 2);
                    controller.updateSelectedModal({keyCode: 39}, 0);
                });
            });
```
> It looks like the results data may already be set, I may have another look tomorrow.

**Comment by RonanC** [comment]
Thanks for the information.
I'll give that a go 👍

Won't be able to get to it for a couple of days yet.

**Comment by miller45** [comment]
@RonanDConnolly I did some refactoring with the modals yesterday and added also the keyboard support for the image modal, so just lean back and don´t be dissapointed when I "reject" this pullrequest.
But you will have that feature soon (today or tomorrow) released.

**Comment by RonanDConnolly** [comment]
Would have been nice to get this PR in, but I'm glad to see the feature being added!

**Comment by miller45** [comment]
I did a manual merge...now you commit is in the master...your solution is  better testable than mine...so i will include it in my refactoring

**Pull request closed without merging**
