### PR TITLE
Fixed Issue #66

### PR DESCRIPTION
**Pull request by keymandll**
Fixed issue #66.

* All buttons should now work.
* Warning sign now should be visible.
* Progress bar counter should be working as well.

### CODE REVIEW

**Comment by cstraynor** [comment]
@evilweed can you take a look at this PR?

**Comment by cstraynor** [comment]
@Evilweed please review this PR and, if accepted, bump up the version number for NPM. Thanks!

**Comment by Mechatrix** [comment]
@Evilweed please review and submit for npm .we are waiting for the fix.

**Comment by Evilweed** [comment]
@Mechatrix @keymandll @cstraynor - sadly I lack time to work on this reporter. But I am willing to add someone as maintainer. Let me know what You think.

**Comment by Mechatrix** [comment]
@Evilweed ..I am good with that.But as of today ..the reporter is completely not good..lost it's beauty.Please spare sometime and push the changes and give new NPM version

**Comment by Evilweed** [comment]
@Mechatrix @keymandll @cstraynor published.

**Comment by cstraynor** [comment]
Thanks @Evilweed ! I'm fine with being added as a maintainer to help keep this awesome project alive.

**Pull request merged**
